# Generated by Django 2.2 on 2019-06-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genere',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Terror', 'Terror'), ('Animate', 'Aminate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languaje',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English'), ('France', 'France')], max_length=50),
        ),
    ]
