# Generated by Django 2.2 on 2019-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0002_auto_20190607_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, upload_to='Escritorio/'),
        ),
    ]
