# Generated by Django 2.2 on 2019-06-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0003_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
