# Generated by Django 2.2 on 2019-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0004_remove_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_rate',
            name='coment',
            field=models.CharField(choices=[('1', 'Mala'), ('2', 'Regular'), ('3', 'Buena'), ('4', 'Muy buena'), ('5', 'Excelente')], max_length=30),
        ),
    ]
