# Generated by Django 2.2 on 2019-06-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0009_auto_20190607_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(null=True),
        ),
    ]
