# Generated by Django 2.2 on 2019-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0010_auto_20190607_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
