# Generated by Django 2.2 on 2019-06-07 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0011_auto_20190607_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
