# Generated by Django 2.2 on 2019-06-12 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoviesApp', '0012_auto_20190607_2240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie_rate',
            unique_together={('user', 'movie')},
        ),
    ]
