# Generated by Django 2.2 on 2019-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0013_auto_20190612_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=100)),
                ('detail_movie', models.CharField(max_length=100)),
                ('trailer_url', models.CharField(max_length=100)),
            ],
        ),
    ]
